### ISSUE TITLE
TypeError: conv2d(): argument 'padding' must be tuple of ints, but found element of type NoneType at pos 1

### ISSUE THREAD

**Issue by baiwan0** [dengbuqi/Gsconv#1]
我用了之后为什么出现这种错误
TypeError: conv2d(): argument 'padding' must be tuple of ints, but found element of type NoneType at pos 1
或者这种RuntimeError: non-positive stride is not supported

**Comment by dengbuqi** [comment]
请您贴上详细的Error信息和torch版本等您觉得有利于Debug的信息，这样我好定位到具体的Error发生的代码位置。

**Comment by baiwan0** [comment]
> 请您贴上详细的Error信息和torch版本等您觉得有利于Debug的信息，这样我好定位到具体的Error发生的代码位置。

![1656898747247](https://user-images.githubusercontent.com/108448679/177066989-94a54491-d295-4710-9f28-c70b322c8cb0.jpg)

**Comment by dengbuqi** [comment]
> > 请您贴上详细的Error信息和torch版本等您觉得有利于Debug的信息，这样我好定位到具体的Error发生的代码位置。
> 
> ![1656898747247](https://user-images.githubusercontent.com/108448679/177066989-94a54491-d295-4710-9f28-c70b322c8cb0.jpg)

根据错误信息的提示，我猜这可能是您构建GSConv实例的时候stride的值被你设置成了负数，请你检查一下您的stride值设置是否正确。

**Comment by baiwan0** [comment]
> > > 请您贴上详细的Error信息和torch版本等您觉得有利于Debug的信息，这样我好定位到具体的Error发生的代码位置。
> > 
> > 
> > ![1656898747247](https://user-images.githubusercontent.com/108448679/177066989-94a54491-d295-4710-9f28-c70b322c8cb0.jpg)
> 
> 根据错误信息的提示，我猜这可能是您构建GSConv实例的时候stride的值被你设置成了负数，请你检查一下您的stride值设置是否正没有呢，我的代码，完全是按照

**Comment by baiwan0** [comment]
> > > > 请您贴上详细的Error信息和torch版本等您觉得有利于Debug的信息，这样我好定位到具体的Error发生的代码位置。
> > > 
> > > 
> > > ![1656898747247](https://user-images.githubusercontent.com/108448679/177066989-94a54491-d295-4710-9f28-c70b322c8cb0.jpg)
> > 
> > 
> > 根据错误信息的提示，我猜这可能是您构建GSConv实例的时候stride的值被你设置成了负数，请你检查一下您的stride值设置是否正没有呢，我的代码，完全是按照

没有呢，我只用用的你的，没有设置成负数，我以为是padding错误了，也尝试修改过

**Comment by dengbuqi** [comment]
> > > > > 请您贴上详细的Error信息和torch版本等您觉得有利于Debug的信息，这样我好定位到具体的Error发生的代码位置。
> > > > 
> > > > 
> > > > ![1656898747247](https://user-images.githubusercontent.com/108448679/177066989-94a54491-d295-4710-9f28-c70b322c8cb0.jpg)
> > > 
> > > 
> > > 根据错误信息的提示，我猜这可能是您构建GSConv实例的时候stride的值被你设置成了负数，请你检查一下您的stride值设置是否正没有呢，我的代码，完全是按照
> 
> 没有呢，我只用用的你的，没有设置成负数，我以为是padding错误了，也尝试修改过

我没有你的代码，请原谅我无法完整的Debug,我自己的测试都是通过了的。
